#!/bin/bash

build() {
    add_binary /etc/processdev/processdev
    add_binary /usr/bin/smdev
    add_binary /usr/bin/nldev
    add_binary /usr/bin/nltrigger
    add_binary /usr/bin/modprobe_env
    add_binary /usr/bin/libudev-helper

    for file in /etc/processdev/add/*; do
        add_file $file
    done

    add_runscript
}

help() {
    cat <<HELPEOF
This hook will use nldev to process device uevents. It prepares your root device and adds some else device nodes.
HELPEOF
}
